name: 刷步数

on:
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]
  schedule:
    - cron: '8 0,2,5,7,9,11,13 * * *'
  watch:
    types: started
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v3
      - name: Update system and install zsh
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get install zsh -y
          
      - name: 初始化Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: 开始
        env:
          USER: ${{secrets.USER }}
          PWD: ${{secrets.PWD }}
          SKEY: ${{secrets.SKEY }}
          SCKEY: ${{secrets.SCKEY }}
          POSITION: ${{secrets.POSITION }}
          CORPID: ${{secrets.CORPID }}
          CORPSECRET: ${{secrets.CORPSECRET }}
          agentid: ${{secrets.AGENTID }}
          AGENTID: ${{secrets.TOUSER }}
          toparty: ${{secrets.TOPARTY }}
          TOPARTY: ${{secrets.TOTAG }}
          open_get_weather: ${{secrets.OPEN_GET_WEATHER }}
          OPEN_GET_WEATHER: ${{secrets.AREA }}
          QWEATHER: ${{secrets.QWEATHER }}
        run: |
          pip3 install requests
          python3 main.py
